# Playbook to setup the OpenStack platform with the server instances required for the QA environment

# This play uses the osp-servers role to create the server instances
---

- hosts: localhost
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    OPENTLC_ID: "{{ lookup('env','OPENTLC_ID') }}"
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.{{OSP_DOMAIN}}"
       group: workstation
       ansible_user: cloud-user     

- hosts: workstation
  become: yes
  become_user = root
  roles:
    - osp-servers

