---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  yum_repository:
    name: "{{ repo.name }}"
    description: "{{ repo.description }}"
    baseurl: "{{ repo.baseurl }}"
    enabled: yes
    gpgcheck: no
    state: present
  loop:
    "{{ repos }}"
  loop_control:
    loop_var: repo

- name: Add EPEL repo
  yum_repository:
    name: "epel"
    description: "Extra Packages for Enterprise Linux 7 - $basearch"
    baseurl: "https://download.fedoraproject.org/pub/epel/7/$basearch/"
    mirrorlist: "http://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch"
    enabled: yes
    gpgcheck: no
    state: present
 
- name: install base tools and packages
  yum:
    name: "{{ package }}"
    state: latest
  loop:
    - httpie
    - python-pip
  loop_control:
    loop_var: package

